
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]

 ignored = [
    #"golang.org/x/text/encoding",
    #"golang.org/x/image/math/fixed",
    #"golang.org/x/image/font",
    #"github.com/golang/freetype",
    #"golang.org/x/text",
    "github.com/jsix/gof",
    "github.com/jsix/goex",
    "github.com/garyburd/redigo/redis",
    "github.com/labstack/echo"
 ]

